import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { discoverSkills, loadAskSkills, skillDirs } from "../src/llm/skills";
import { writeKnowledgeSkill, SKILL_TARGETS } from "../src/covault/skill";

let vault: string;
let home: string;
const OVERRIDES = ["HOME", "USERPROFILE", "PI_CODING_AGENT_DIR", "CODEX_HOME"] as const;
const realEnv = Object.fromEntries(OVERRIDES.map((k) => [k, process.env[k]]));

/** A skill in the standard shape: SKILL.md in a folder of its own. */
function writeSkill(dir: string, name: string, description: string, body = "Do the thing.", extra?: Record<string, string>) {
  const skillDir = path.join(dir, name);
  fs.mkdirSync(skillDir, { recursive: true });
  const front = ["---", `name: ${name}`, `description: ${description}`, ...(extra ? Object.entries(extra).map(([k, v]) => `${k}: ${v}`) : []), "---", "", body, ""];
  fs.writeFileSync(path.join(skillDir, "SKILL.md"), front.join("\n"));
  return skillDir;
}

beforeEach(() => {
  vault = fs.mkdtempSync(path.join(os.tmpdir(), "covault-skills-"));
  home = fs.mkdtempSync(path.join(os.tmpdir(), "covault-home-"));
  // os.homedir() reads these, so the user's real skills stay out of the test.
  process.env.HOME = home;
  process.env.USERPROFILE = home;
  delete process.env.PI_CODING_AGENT_DIR;
  delete process.env.CODEX_HOME;
});
afterEach(() => {
  fs.rmSync(vault, { recursive: true, force: true });
  fs.rmSync(home, { recursive: true, force: true });
  for (const key of OVERRIDES) {
    const value = realEnv[key];
    if (value === undefined) delete process.env[key];
    else process.env[key] = value;
  }
});

describe("skillDirs", () => {
  it("covers every agent, both scopes, project first", () => {
    expect(skillDirs(vault)).toEqual([
      path.join(vault, ".claude", "skills"),
      path.join(vault, ".pi", "skills"),
      path.join(vault, ".codex", "skills"),
      path.join(home, ".claude", "skills"),
      path.join(home, ".pi", "agent", "skills"),
      path.join(home, ".codex", "skills"),
    ]);
  });

  it("honours each agent's own home override", () => {
    process.env.PI_CODING_AGENT_DIR = "/opt/pi";
    process.env.CODEX_HOME = "/opt/codex";
    expect(skillDirs(vault)).toContain(path.join("/opt/pi", "skills"));
    expect(skillDirs(vault)).toContain(path.join("/opt/codex", "skills"));
  });
});

describe("discoverSkills", () => {
  it("finds Claude Code, pi and Codex skills in the vault and in the user's home", async () => {
    writeSkill(path.join(vault, ".claude", "skills"), "vault-claude", "Vault skill for Claude Code.");
    writeSkill(path.join(vault, ".pi", "skills"), "vault-pi", "Vault skill for pi.");
    writeSkill(path.join(vault, ".codex", "skills"), "vault-codex", "Vault skill for Codex.");
    writeSkill(path.join(home, ".claude", "skills"), "home-claude", "Personal skill for Claude Code.");
    writeSkill(path.join(home, ".pi", "agent", "skills"), "home-pi", "Personal skill for pi.");
    writeSkill(path.join(home, ".codex", "skills"), "home-codex", "Personal skill for Codex.");

    const names = (await discoverSkills(vault)).map((s) => s.name).sort();
    expect(names).toEqual(["home-claude", "home-codex", "home-pi", "vault-claude", "vault-codex", "vault-pi"]);
  });

  it("leaves Codex's own preinstalled .system skills out", async () => {
    writeSkill(path.join(home, ".codex", "skills", ".system"), "imagegen", "Codex's built-in image tooling.");
    writeSkill(path.join(home, ".codex", "skills"), "mine", "A skill I installed.");

    expect((await discoverSkills(vault)).map((s) => s.name)).toEqual(["mine"]);
  });

  it("gives the vault's own skill the name when a personal one collides", async () => {
    writeSkill(path.join(vault, ".claude", "skills"), "review", "Vault version.", "Vault instructions.");
    writeSkill(path.join(home, ".claude", "skills"), "review", "Personal version.", "Personal instructions.");

    const found = await discoverSkills(vault);
    expect(found).toHaveLength(1);
    expect(found[0]!.content).toContain("Vault instructions.");
  });

  it("skips the excluded files (ours) and anything without a description", async () => {
    const dir = path.join(vault, ".claude", "skills");
    writeSkill(dir, "team-knowledge", "Generated by Covault.");
    writeSkill(dir, "keeper", "A real skill.");
    fs.mkdirSync(path.join(dir, "broken"), { recursive: true });
    fs.writeFileSync(path.join(dir, "broken", "SKILL.md"), "---\nname: broken\n---\n\nNo description.\n");

    const found = await discoverSkills(vault, [path.join(dir, "team-knowledge", "SKILL.md")]);
    expect(found.map((s) => s.name)).toEqual(["keeper"]);
  });

  it("returns nothing for a vault with no skills anywhere", async () => {
    expect(await discoverSkills(vault)).toEqual([]);
  });
});

describe("loadAskSkills", () => {
  it("is null when there is nothing to advertise", async () => {
    expect(await loadAskSkills(vault)).toBeNull();
  });

  it("lists each skill by name and description only — the body waits for load_skill", async () => {
    writeSkill(path.join(vault, ".claude", "skills"), "deploy", "Ship the service. Use when asked to deploy.", "Step 1: run the pipeline.");

    const skills = await loadAskSkills(vault);
    expect(skills).not.toBeNull();
    expect(skills!.prompt).toContain("<name>deploy</name>");
    expect(skills!.prompt).toContain("Use when asked to deploy.");
    expect(skills!.prompt).not.toContain("Step 1"); // progressive disclosure
    expect(skills!.tools.map((t) => t.name)).toEqual(["load_skill"]);
  });

  it("load_skill returns the instructions, and support files beside them", async () => {
    const dir = writeSkill(path.join(vault, ".pi", "skills"), "charts", "Draw charts.", "See references/palette.md.");
    fs.mkdirSync(path.join(dir, "references"), { recursive: true });
    fs.writeFileSync(path.join(dir, "references", "palette.md"), "# Palette\nBlue first.\n");

    const tool = (await loadAskSkills(vault))!.tools[0]!;
    expect(tool.needsApproval).toBeUndefined(); // read-only, the user's own files

    const body = await tool.execute({ name: "charts" });
    expect(body.text).toContain("See references/palette.md.");
    expect(body.text).toContain('<skill name="charts"');

    const support = await tool.execute({ name: "charts", file: "references/palette.md" });
    expect(support.text).toContain("Blue first.");

    // Escapes and unknown names are answers, not crashes.
    const escape = await tool.execute({ name: "charts", file: "../../../../etc/hosts" });
    expect(escape.isError).toBe(true);
    const missing = await tool.execute({ name: "nope" });
    expect(missing.isError).toBe(true);
    expect(missing.text).toContain("charts"); // says what there is instead
  });

  it("keeps a disable-model-invocation skill out of the listing but loadable by name", async () => {
    const dir = path.join(vault, ".claude", "skills");
    writeSkill(dir, "hidden", "Explicit invocation only.", "Secret steps.", { "disable-model-invocation": "true" });
    writeSkill(dir, "listed", "Ordinary skill.");

    const skills = (await loadAskSkills(vault))!;
    expect(skills.prompt).toContain("<name>listed</name>");
    expect(skills.prompt).not.toContain("<name>hidden</name>");
    expect((await skills.tools[0]!.execute({ name: "hidden" })).text).toContain("Secret steps.");
  });
});

describe("the skill Covault generates", () => {
  it("is an ordinary skill to the loader — found in both folders, excludable by path", async () => {
    fs.mkdirSync(path.join(vault, "teams", "ccp-kb"), { recursive: true });
    fs.writeFileSync(path.join(vault, "teams", "ccp-kb", "refunds.md"), "# Refunds\n");
    writeKnowledgeSkill(vault, [
      { path: "teams/ccp-kb", url: "https://github.com/ct-kb/ccp-kb.git", branch: "main" },
    ]);

    // Found by the same discovery any other agent uses: Claude Code's
    // folder and pi's, deduped to one by name.
    const found = await discoverSkills(vault);
    expect(found.map((s) => s.name)).toEqual(["team-knowledge"]);
    expect(found[0]!.description).toContain("ccp-kb");

    // And left out for our own agent, which already has it inline.
    const excluded = await discoverSkills(vault, SKILL_TARGETS.map((t) => path.join(vault, t)));
    expect(excluded).toEqual([]);
  });
});
