/**
 * Generates the vault's knowledge-routing skill: a plain Markdown file
 * that tells any AI agent working in this vault which knowledge library
 * answers which kind of question, and how to look inside it.
 *
 * The format follows the Agent Skills convention (YAML frontmatter with
 * name/description, instructions in the body) but is deliberately just
 * Markdown — usable by anything that can read a file.
 *
 * The file is DERIVED DATA, rebuilt from the manifest and the libraries'
 * own content after every sync. It is never synced anywhere: each device
 * regenerates its own (see ALWAYS_EXCLUDED and the managed .gitignore
 * block), so it can never cause a merge conflict.
 */
import * as fs from "fs";
import * as path from "path";
import type { ManifestRepo } from "./manifest";
import { repoNameFromUrl } from "../git/urls";

export const SKILL_RELPATH = ".covault/skills/team-knowledge.md";

/** Walk caps: a routing index needs shape, not an exhaustive census. */
const MAX_FILES_COUNTED = 5000;
const MAX_TOP_ENTRIES = 12;
const README_EXCERPT_CHARS = 400;

interface LibraryFacts {
  repo: ManifestRepo;
  name: string;
  noteCount: number;
  topEntries: string[]; // "guides/ (12 notes)" or "faq.md"
  readmeExcerpt: string | null;
  readmePath: string | null;
}

/** Recursively count .md files, skipping git internals. Capped. */
function countNotes(dir: string, budget: { left: number }): number {
  let count = 0;
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return 0;
  }
  for (const e of entries) {
    if (budget.left <= 0) return count;
    if (e.name === ".git" || e.name === ".covault") continue;
    if (e.isDirectory()) {
      count += countNotes(path.join(dir, e.name), budget);
    } else if (e.name.toLowerCase().endsWith(".md")) {
      count += 1;
      budget.left -= 1;
    }
  }
  return count;
}

/** First meaningful lines of a README, headings stripped down to text. */
function readmeExcerpt(file: string): string | null {
  let raw: string;
  try {
    raw = fs.readFileSync(file, "utf8");
  } catch {
    return null;
  }
  // Drop frontmatter, keep the first prose lines.
  const body = raw.replace(/^---\n[\s\S]*?\n---\n/, "");
  const lines = body
    .split("\n")
    .map((l) => l.replace(/^#+\s*/, "").trim())
    .filter((l) => l.length > 0);
  if (lines.length === 0) return null;
  let out = "";
  for (const line of lines) {
    if (out.length >= README_EXCERPT_CHARS) break;
    out += (out ? " " : "") + line;
  }
  return out.length > README_EXCERPT_CHARS ? `${out.slice(0, README_EXCERPT_CHARS)}…` : out;
}

function gatherFacts(vaultBase: string, repo: ManifestRepo): LibraryFacts {
  const dir = path.join(vaultBase, repo.path);
  const name = repoNameFromUrl(repo.url);

  let topEntries: string[] = [];
  let readmeFile: string | null = null;
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    const dirs = entries
      .filter((e) => e.isDirectory() && e.name !== ".git" && !e.name.startsWith("."))
      .map((e) => {
        const n = countNotes(path.join(dir, e.name), { left: MAX_FILES_COUNTED });
        return { label: `${e.name}/ (${n} note${n === 1 ? "" : "s"})`, notes: n };
      })
      .sort((a, b) => b.notes - a.notes);
    const files = entries
      .filter((e) => e.isFile() && e.name.toLowerCase().endsWith(".md"))
      .map((e) => e.name)
      .sort();
    const readmeName = files.find((f) => f.toLowerCase() === "readme.md");
    if (readmeName) readmeFile = path.join(dir, readmeName);
    topEntries = [...dirs.map((d) => d.label), ...files].slice(0, MAX_TOP_ENTRIES);
  } catch {
    /* folder missing (not cloned yet) — still list the library */
  }

  return {
    repo,
    name,
    noteCount: countNotes(dir, { left: MAX_FILES_COUNTED }),
    topEntries,
    readmeExcerpt: readmeFile ? readmeExcerpt(readmeFile) : null,
    readmePath: readmeFile ? path.join(repo.path, path.basename(readmeFile)) : null,
  };
}

/** Build the full skill document. Deterministic for identical vault state. */
export function buildKnowledgeSkill(vaultBase: string, repos: ManifestRepo[]): string {
  const facts = [...repos].sort((a, b) => a.path.localeCompare(b.path)).map((r) => gatherFacts(vaultBase, r));
  const names = facts.map((f) => f.name).slice(0, 15);

  const description =
    facts.length === 0
      ? "No team knowledge libraries are installed in this vault yet."
      : `Routes questions to the team knowledge libraries in this vault (${names.join(", ")}). ` +
        "Consult the matching library folder before answering anything these topics touch.";

  const lines: string[] = [
    "---",
    "name: team-knowledge",
    `description: ${description}`,
    "---",
    "",
    "# Team knowledge libraries",
    "",
    "<!-- Generated by Covault. Do not edit: rebuilt after every sync. -->",
    "",
    "Each folder below is a knowledge library shared by the team and kept",
    "in sync automatically. When a question touches one of these topics,",
    "read the matching folder before answering from general knowledge —",
    "the library is the source of truth.",
    "",
    "How to look inside a library:",
    "",
    "1. Start from its README or the entry notes listed under *Contents*.",
    "2. Otherwise scan file names and headings of the `*.md` files in the folder.",
    "3. When notes disagree, prefer the most recently modified one.",
    "",
  ];

  if (facts.length === 0) {
    lines.push("_No libraries installed yet. Add one via the Covault panel._", "");
  }

  for (const f of facts) {
    lines.push(`## ${f.name} — \`${f.repo.path}/\``, "");
    lines.push(`- Source: ${f.repo.url.replace(/\.git$/, "")} (${f.repo.branch})`);
    lines.push(`- Size: ${f.noteCount} note${f.noteCount === 1 ? "" : "s"}`);
    if (f.readmePath) lines.push(`- Start here: \`${f.readmePath}\``);
    if (f.topEntries.length > 0) lines.push(`- Contents: ${f.topEntries.join(", ")}`);
    if (f.readmeExcerpt) lines.push("", `> ${f.readmeExcerpt}`);
    lines.push("");
  }

  return lines.join("\n");
}

/** Write the skill file iff its content changed. Returns whether it did. */
export function writeKnowledgeSkill(vaultBase: string, repos: ManifestRepo[]): boolean {
  const file = path.join(vaultBase, SKILL_RELPATH);
  const next = buildKnowledgeSkill(vaultBase, repos);
  let current: string | null = null;
  try {
    current = fs.readFileSync(file, "utf8");
  } catch {
    /* first run */
  }
  if (current === next) return false;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, next);
  return true;
}
